Add callback authentication support

diff --git a/scripts/nord_login b/scripts/nord_login
--- a/scripts/nord_login
+++ b/scripts/nord_login
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+PREVIOUS_CALLBACK_FILE="/var/lib/nordvpn/previous_callback.txt"
+
 if ! iptables -L > /dev/null 2>&1
 then
   echo -e "$(date "+%F %T%z")\tWARNING\tiptables is not functional. Ensure your container capabilities include NET_ADMIN" 1>&2
@@ -16,17 +18,39 @@ then
   done
 fi
 
-## only token is viable in a container
-nordvpn logout --persist-token > /dev/null 2>&1
-if [[ -n ${TOKEN} ]]
+[[ -f "${PREVIOUS_CALLBACK_FILE}" ]] && PREVIOUS_CALLBACK="$(head -n 1 "${PREVIOUS_CALLBACK_FILE}")"
+
+if [[ -n $PREVIOUS_CALLBACK ]]
 then
-  nordvpn login --token "${TOKEN}" > /dev/null || {
-    echo -e "$(date "+%F %T%z")\tWARNING\tInvalid token."
-    exit 1
-  }
+  echo -e "$(date "+%F %T%z")\tINFO\tPreviously logged in with callback, skipping authentication."
 else
-    echo -e "$(date "+%F %T%z")\tWARNING\tA token must be provided; only tokens are supported."
+  nordvpn logout --persist-token > /dev/null 2>&1
+  rm -f $PREVIOUS_CALLBACK_FILE
+  if [[ -n ${TOKEN} ]]
+  then
+    nordvpn login --token "${TOKEN}" > /dev/null || {
+      echo -e "$(date "+%F %T%z")\tWARNING\tInvalid token."
+      exit 1
+    }
+  else
+    if [[ -t 0 ]]
+    then
+      /usr/local/bin/nord_login_callback || {
+        echo -e "$(date "+%F %T%z")\tWARNING\tInteractive login failed."
+        exit 1
+      }
+    else
+      echo -e "$(date "+%F %T%z")\tINFO\tPlease start the interactive login process by executing the following command on the host:"
+      echo -e "$(date "+%F %T%z")\tINFO\tdocker exec -i $(cat /etc/hostname) nord_login_callback"
+      while [ ! -f $PREVIOUS_CALLBACK_FILE ]
+      do
+        echo -e "$(date "+%F %T%z")\tINFO\tWaiting for interactive login process to complete..."
+        sleep 2s
+      done
+    fi
+  fi
 fi
+
 ## Clear sensitive variables
 echo "Login successful; connection now in progress..."
 exit 0
